networks:
  test:
    name: test

services:
  mockserver:
    container_name: mockserver
    image: mockserver/mockserver
    ports:
      - 1080:1080
    networks:
      test:
        aliases:
          - mockserver
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/expectations.json
    volumes:
      - ./config:/config

