name: aws-sam-cli

on:
  workflow_dispatch:
  push:

jobs:
  aws-sam-test:
    runs-on: ubuntu-latest
    steps:
      - run: sam init --no-interactive --name sam-app --runtime python3.9 --dependency-manager pip --app-template hello-world
      - run: cd sam-app && sam build --use-container --debug
      - run: cd sam-app && sam local invoke "HelloWorldFunction" -e events/event.json
      - run: cd sam-app && sam local generate-event apigateway aws-proxy --body "" --path "hello" --method GET
