name: mockserver

on:
  workflow_dispatch:

jobs:
  mockserver-test:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check versions
        run: |
          docker --version
          docker-compose --version

      - name: test running and connecting to mockserver
        run: |
          docker pull -q mockserver/mockserver
          docker pull -q alpine
          cd mockserver
          docker-compose up -d 
          curl --retry 10 --retry-all-errors --retry-delay 5 -X PUT http://localhost:1080/mockserver/status
          curl -X GET http://localhost:1080/hello
          docker run --name alpine --network test -t -d alpine
          docker exec alpine apk add curl
          docker exec alpine curl -X GET http://mockserver:1080/hello
      
      - name: mockserver logs
        if: ${{ always() }}
        run: docker logs mockserver

  mockserver-dind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check versions
        run: |
          docker --version
          docker-compose --version

      - name: test running and connecting to mockserver
        run: |
          docker pull -q docker
          docker run -t -d docker sh -c "
            docker info;\
            docker run --privileged -d docker:dind;\
            docker info;\
          "
