name: mockserver

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  mockserver-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check versions
        run: |
          docker --version
          docker-compose --version
          docker info
          uname -a

      - name: test running and connecting to mockserver
        run: |
          docker pull -q mockserver/mockserver
          docker pull -q alpine
          cd mockserver
          docker-compose up -d 
          # curl --retry 10 --retry-all-errors --retry-delay 5 -X PUT http://localhost:8080/mockserver/status
          # curl -X GET http://localhost:8080/hello
          docker run --name alpine --rm --network test alpine /bin/sh -c "apk add curl"
          docker exec alpine uname -a
          docker exec alpine curl -X GET http://mockserver:8080/hello
