name: mockserver

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  mockserver-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check versions
        run: |
          docker --version
          docker-compose --version
          docker info

      - name: test running and connecting to mockserver
        run: |
          docker pull mockserver/mockserver
          docker pull alpine
          cd mockserver
          docker-compose up -d 
          curl --retry 2 --retry-all-errors --retry-delay 5 -X PUT http://docker:8080/mockserver/status
          curl -X GET http://docker:8080/hello
          docker run --name alpine --rm --network test alpine \
            curl -X GET http://mockserver:8080/hello
          
